name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install dependencies
      run: pip install .
    - name: All tests
      run: pytest tests -v

